/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Multicall } from "./Multicall";

export { Erc20__factory } from "./factories/Erc20__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
